[FSR]
profile-desc=FidelityFX Super Resolution
glsl-shaders="~~/shaders/FSR.glsl"

[NNEDI3]
profile-desc=Suitable for most scenarios
glsl-shaders="~~/shaders/nnedi3/nnedi3-nns32-win8x4.glsl:~~/shaders/igv/KrigBilateral.glsl:~~/shaders/igv/SSimDownscaler.glsl"

[NNEDI3+]
profile-desc=Suitable for most scenarios
glsl-shaders="~~/shaders/nnedi3/nnedi3-nns64-win8x4.glsl:~~/shaders/igv/KrigBilateral.glsl:~~/shaders/igv/SSimDownscaler.glsl"

[ravu-zoom]
profile-desc=Suitable for most scenarios
glsl-shaders="~~/shaders/ravu/ravu-zoom-ar-r3.glsl:~~/shaders/igv/KrigBilateral.glsl:~~/shaders/igv/SSimDownscaler.glsl"

[FSRCNNX]
profile-desc=Suitable for HD scenarios
glsl-shaders="~~/shaders/igv/FSRCNNX_x2_8-0-4-1.glsl:~~/shaders/igv/KrigBilateral.glsl:~~/shaders/igv/SSimSuperRes.glsl:~~/shaders/igv/SSimDownscaler.glsl"

[FSRCNNX+]
profile-desc=Suitable for SD scenarios
glsl-shaders="~~/shaders/igv/FSRCNNX_x1_16-0-4-1_distort.glsl:~~/shaders/igv/KrigBilateral.glsl:~~/shaders/ravu/ravu-zoom-ar-r3.glsl:~~/shaders/igv/SSimDownscaler.glsl"

[Anime4K]
profile-desc=Suitable for most animations
glsl-shaders="~~/shaders/Anime4K/Anime4K_Clamp_Highlights.glsl:~~/shaders/Anime4K/Anime4K_Restore_CNN_VL.glsl:~~/shaders/Anime4K/Anime4K_Upscale_CNN_x2_VL.glsl:~~/shaders/Anime4K/Anime4K_AutoDownscalePre_x2.glsl:~~/shaders/Anime4K/Anime4K_AutoDownscalePre_x4.glsl:~~/shaders/Anime4K/Anime4K_Upscale_CNN_x2_M.glsl"

[SSIM]
profile-desc=Suitable for 4K low performance
glsl-shaders="~~/shaders/igv/SSimSuperRes.glsl:~~/shaders/igv/SSimDownscaler.glsl"