# Expression generated by update.sh; do not edit it by hand!
{ stdenv, callPackage, ... }@args:

let
  pname = "brave-origin";
  version = "1.92.81";

  allArchives = {
    x86_64-linux = {
      url = "https://github.com/brave/brave-browser/releases/download/v${version}/brave-origin-nightly_${version}_amd64.deb";
      hash = "sha256-bblhHxcIVbTiWJ35nr45jEWNRz1Yxr8qNp2Nn38nVU8=";
    };
  };

in
callPackage ./make-brave.nix (removeAttrs args [ "callPackage" ]) {
  inherit pname version;
  archives = allArchives;
}
