#!/usr/bin/env nix-shell
#!nix-shell -i bash -p curl nix jq

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"

# Fetch release metadata
releasesJson="$(curl --fail -s ${GITHUB_TOKEN:+-u ":$GITHUB_TOKEN"} "https://api.github.com/repos/brave/brave-browser/releases?per_page=20")"

# Filter for the latest nightly release containing an amd64 .deb
releaseJson="$(
  jq -c '
    map(
      select(.prerelease)
      | .tag_name as $tag
      | .assets as $assets
      | select(any($assets[]?.name; . == ("brave-origin-nightly_" + ($tag | ltrimstr("v")) + "_amd64.deb")))
    )
    | first
  ' <<<"$releasesJson"
)"

latestVersion="$(jq -r '.tag_name | ltrimstr("v")' <<<"$releaseJson")"

if [[ -z "$latestVersion" || "$latestVersion" == "null" ]]; then
  echo "Could not determine latest brave-origin version." >&2
  exit 1
fi

# Helper to verify asset existence
hasAsset() {
  jq -e --arg name "$1" 'any(.assets[]?.name; . == $name)' <<<"$releaseJson" >/dev/null
}

# Ensure the x86_64 Linux asset exists
requireAsset() {
  if ! hasAsset "$1"; then
    echo "Missing expected asset: $1" >&2
    exit 1
  fi
}

requireAsset "brave-origin-nightly_${latestVersion}_amd64.deb"

# Fetch hash for x86_64-linux only
hashAmd64="$(nix-hash --to-sri --type sha256 "$(nix-prefetch-url --type sha256 "https://github.com/brave/brave-browser/releases/download/v${latestVersion}/brave-origin-nightly_${latestVersion}_amd64.deb")")"

# Generate package.nix
cat >"$SCRIPT_DIR/package.nix" <<EOF
# Expression generated by update.sh; do not edit it by hand!
{ stdenv, callPackage, ... }@args:

let
  pname = "brave-origin";
  version = "${latestVersion}";

  allArchives = {
    x86_64-linux = {
      url = "https://github.com/brave/brave-browser/releases/download/v\${version}/brave-origin-nightly_\${version}_amd64.deb";
      hash = "${hashAmd64}";
    };
  };

in
callPackage ./make-brave.nix (removeAttrs args [ "callPackage" ]) {
  inherit pname version;
  archives = allArchives;
}
EOF