#!/usr/bin/env bash
MOD=5

check() {
  command -v "$1" 1>/dev/null
}

notify() {
  check notify-send && notify-send -a "Volume" "$@" || echo "$@"
}

check pamixer || {
  notify "Pamixer is not present"
  exit 1
}

is_muted=$(pamixer --get-mute)

getVolume() {
  pamixer --get-volume
}

send_notification() {
  local current_mute=$(pamixer --get-mute)
  local vol_val=$(getVolume)
  local vol_text

  if [ "$current_mute" = "true" ]; then
    vol_val=0
    vol_text="Muted"
  else
    vol_text="Volume: ${vol_val}%"
  fi

  notify \
    --hint=string:x-dunst-stack-tag:volume \
    --hint=string:synchronous:volume \
    -u low \
    -h int:value:"$vol_val" "$vol_text" \
    -t 1000
}

case $1 in
up)
  [ "$is_muted" = "true" ] && pamixer -u
  
  pamixer -i "$MOD"
  send_notification
  ;;
down)
  [ "$is_muted" = "true" ] && pamixer -u
  
  pamixer -d "$MOD"
  send_notification
  ;;
mute)
  pamixer -t
  send_notification
  ;;
esac