###################
### KEYBINDINGS ###
###################
# https://wiki.hyprland.org/Configuring/Keywords/
# https://wiki.hyprland.org/Configuring/Binds/
# Note: Application variables are defined in the main hyprland.conf

# Main modifier key
$mainMod = SUPER  # Windows key as main modifier

# App shortcuts
bind = $mainMod, Return, exec, $terminal
bind = $mainMod SHIFT, Return, exec, hyprctl dispatch exec "[float;size 1120 630] $terminal"
bind = $mainMod, B, exec, $browser
bind = $mainMod, C, exec, $editor
bind = $mainMod, E, exec, $fileManager

# Rofi executables
bind = $mainMod, M, exec, $powerMenu
bind = $mainMod, S, exec, $menu
bind = $mainMod, TAB, exec, $windowSwitcher

# Window control
bind = $mainMod, Q, killactive,
bind = $mainMod, W, togglefloating,
bind = $mainMod, F, fullscreen,
bind = $mainMod, U, togglesplit,  # dwindle split toggle
bind = $mainMod, I, swapsplit,  # swaps the two halves of the split
bind = $mainMod, K, exec, exec ~/.config/hypr/scripts/cycle_kb_layout.sh

# Focus movement
bind = $mainMod, left, movefocus, l
bind = $mainMod, right, movefocus, r
bind = $mainMod, up, movefocus, u
bind = $mainMod, down, movefocus, d

# Workspaces
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9

# Move window to workspace
bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5
bind = $mainMod SHIFT, 6, movetoworkspace, 6
bind = $mainMod SHIFT, 7, movetoworkspace, 7
bind = $mainMod SHIFT, 8, movetoworkspace, 8
bind = $mainMod SHIFT, 9, movetoworkspace, 9

# Move window to first empty workspace
bind = $mainMod, A, exec, ~/.config/hypr/scripts/move_active_to_empty.sh
bind = $mainMod SHIFT, A, exec, ~/.config/hypr/scripts/move_active_to_empty_silent.sh

# Scroll through workspaces
bind = $mainMod, mouse_down, workspace, e+1
bind = $mainMod, mouse_up, workspace, e-1

# Window move/resize (mouse)
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow
bindm = $mainMod, Z, movewindow
bindm = $mainMod, X, resizewindow

# Window resize (keyboard)
binde = $mainMod+Shift, Right, resizeactive, 30 0
binde = $mainMod+Shift, Left, resizeactive, -30 0
binde = $mainMod+Shift, Up, resizeactive, 0 -30
binde = $mainMod+Shift, Down, resizeactive, 0 30

# System control
bind = Ctrl, Escape, exec, ~/.config/waybar/scripts/toggle_waybar.sh # Toggle waybar
bind = $mainMod, P, exec, hyprshot -zm region -o ~/Pictures/Screenshots  # Screenshot

# Audio
bind = , XF86AudioRaiseVolume, exec,  ~/.config/hypr/scripts/volume up
bind = , XF86AudioLowerVolume, exec, ~/.config/hypr/scripts/volume down
bind = , XF86AudioMute, exec, ~/.config/hypr/scripts/volume mute


# Brightness
bind = , XF86MonBrightnessUp, exec, brightnessctl s +5%
bind = , XF86MonBrightnessDown, exec, brightnessctl s 5%-
