###############
###  RULES  ###
###############
# https://wiki.hyprland.org/Configuring/Window-Rules/

# Ignore maximize requests from apps.
windowrulev2 = suppressevent maximize, class:.*

# Picture in Picture
windowrulev2 = float, class:^(firefox)$, title:(Picture-in-Picture)
windowrulev2 = size 720 405, title:(Picture-in-Picture)

# Kitty
windowrulev2 = opacity 0.85 override,class:^(kitty)$

# KDE
windowrulev2 = float,stayfocused,center,class:^(plasma-polkit-agent)$
windowrulev2 = float,stayfocused,center,class:^(org.freedesktop.impl.portal.desktop.kde)$


# Calculator (KQalculate!)
windowrulev2 = float,class:^(qalculate-gtk)$

# Pavucontrol (Audio Control)
windowrulev2 = float,class:^(pavucontrol-qt)$
windowrulev2 = size 900 700,class:^(pavucontrol-qt)$
windowrulev2 = center,class:^(pavucontrol-qt)$

# Remmina
windowrulev2 = float,title:^(Remmina Remote Desktop Client)$
windowrulev2 = size 670 760,title:^(Remmina Remote Desktop Client)$

# XIVLauncher and FFXIV
windowrulev2 = float,class:^(XIVLauncher.Core)$
windowrulev2 = fullscreen,class:^(ffxiv_dx11.exe)$

# Overwatch
windowrulev2 = fullscreen,title:^(Overwatch)$

# Rofi
layerrule = dimaround, ^(rofi)$

# Hyprpicker
layerrule = noanim, hyprpicker
layerrule = noanim, selection
layerrule = noanim, slurp