#Behaviour
confirm_os_window_close 0
enable_audio_bell no
linux_display_server auto
scrollback_lines 2000
wheel_scroll_min_lines 1

#Theming
include theme.conf
font_size 12.3
window_padding_width 8
font_family      JetBrainsMono Nerd Font
italic_font      auto
bold_font        auto
bold_italic_font auto

#Keybinds
map ctrl+c copy_and_clear_or_interrupt
map ctrl+f      launch --location=hsplit --allow-remote-control kitty +kitten search.py @active-kitty-window-id